### PR TITLE
Adding history support

### PR DESCRIPTION
**Pull request by omakoto**
Hi, I've added history support to the ST3 version.  Use the UP/DOWN keys in the input box to retrieve previous commands.  The history is saved in ~/.sublimeexternalcommand_history.

### CODE REVIEW

**Comment by greneholt** [comment]
Two requests before I merge this:
1. Could you please make it so either the command line is blank at first, and you have to go up one to get the last item, or show the last command but have it selected. I want them to be able to just start typing immediately without having to erase what they ran last.
2. Make separate command histories for insert and filter, since the commands people will use for them are very different.

**Comment by greneholt** [comment]
If the second one is very difficult, we can skip it.

**Comment by omakoto** [comment]
Second one is doable; we just need to teach the history command which mode we're currently in somehow.  I can think of two ways to do that: 1) Just use a global variable.  Simpler but slightly dirtier.  2)  Use different scopes for the two modes.  We'll need one more language file, two more shortcut keys.  Probably cleaner but kinda overkill.

Which one would you prefer?

**Comment by greneholt** [comment]
Honestly, it's not that big of a deal the more I think about it. Just leave that part as is.

**Comment by omakoto** [comment]
Okay, #1 is done.  And there was a bug in the previous version -- I forgot to reset the history index when showing the input box.

How does it look now?

**Comment by greneholt** [comment]
Looks good, merged.

**Pull request merged**
